# Generated by Django 2.2.5 on 2020-01-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.TextField(default='', max_length=200),
        ),
    ]
