# Generated by Django 2.2.5 on 2020-01-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.TextField(default='', max_length=200),
        ),
    ]
